
export default function Disclaimer() {
  return (
    <div className="container mx-auto px-4 py-8 md:py-16">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-6 text-center">
          Disclaimer
        </h1>
        <p className="text-gray-600 mb-4 text-center">
          Last updated: August 6, 2026
        </p>
        
        <div className="prose lg:prose-xl max-w-none">
          <h2 className="text-2xl font-semibold mb-4 mt-8>General Disclaimer</h2>
          <p>
            The information provided by SentinelX AI is for general informational 
            purposes only. While we strive to keep the information up to date and 
            correct, we make no representations or warranties of any kind, express 
            or implied, about the completeness, accuracy, reliability, suitability, 
            or availability with respect to the website, products, services, or 
            related graphics contained on the website for any purpose.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>Professional Advice Disclaimer</h2>
          <p>
            The information provided through our services is not intended to be 
            a substitute for professional advice. Always seek the advice of 
            qualified professionals with any questions you may have regarding 
            legal, medical, financial, or other professional matters.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>AI-Generated Content Disclaimer</h2>
          <p>
            Content generated by our AI systems should be reviewed and validated 
            by qualified professionals before being used for decision-making. 
            AI-generated content may contain inaccuracies, biases, or incomplete 
            information and should not be relied upon as the sole source of 
            information for critical decisions.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>No Endorsement</h2>
          <p>
            Reference to any specific commercial product, process, or service by 
            trade name, trademark, manufacturer, or otherwise does not constitute 
            or imply its endorsement, recommendation, or favoring by SentinelX AI.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>External Links Disclaimer</h2>
          <p>
            Our website may contain links to external websites that are not 
            maintained by or related to SentinelX AI. We do not guarantee, 
            endorse, or approve the information or products available at these 
            sites, nor does a link indicate any association with or endorsement 
            of the linked site by SentinelX AI.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>Testimonials Disclaimer</h2>
          <p>
            Testimonials and case studies presented on our website reflect 
            individual experiences and results may vary. We do not claim that 
            these results are typical or that similar results will be achieved 
            in all cases.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>Forward-Looking Statements Disclaimer</h2>
          <p>
            This website may contain forward-looking statements that are subject 
            to risks and uncertainties that could cause actual results to differ 
            materially from those expected. These statements are based on current 
            expectations, estimates, forecasts, and projections about the industry 
            and markets in which we operate.
          </p>
          
          <h2 className="text-2xl font-semibold mb-4 mt-8>Contact Us</h2>
          <p>
            If you have any questions about this Disclaimer, please contact us at:
          </p>
          <p className="bg-gray-50 p-4 rounded-lg">
            <strong>Email:</strong> legal@sentinelx.ai<br />
            <strong>Phone:</strong> +91 8125629601
          </p>
        </div>
        
        <div className="mt-10 text-center text-sm text-gray-500 border-t pt-6">
          © 2026 SentinelX AI. All rights reserved.
        </div>
      </div>
    </div>
  );
}